const demos = [];


/*
 * This file is autogenerated from vite
 * via autoimport.js
 * 
 * It contains all components from src/
*/

import "../src/dialog"
import {Demo as Demo0} from "../src/dialog"
demos.push(Demo0)


/*
 * This file is autogenerated from vite
 * via autoimport.js
 * 
 * It contains all components from src/
*/

import "../src/menu"
import {Demo as Demo1} from "../src/menu"
demos.push(Demo1)

import {render} from "preact";
if(typeof window != 'undefined' && window['showcase']) {
  document.addEventListener('DOMContentLoaded', () => {
  render(<div>{demos}</div>, document.body);
  })
}
