
            const demos = [];
            
/*
 * This file is autogenerated from vite
 * via autoimport.js
 * 
 * It contains all components from src/
*/

import "../src/dialog"
import {Demo as Demo0} from "../src/dialog"
demos.push(Demo0)


/*
 * This file is autogenerated from vite
 * via autoimport.js
 * 
 * It contains all components from src/
*/

import "../src/empty"
import {Demo as Demo1} from "../src/empty"
demos.push(Demo1)


/*
 * This file is autogenerated from vite
 * via autoimport.js
 * 
 * It contains all components from src/
*/

import "../src/menu"
import {Demo as Demo2} from "../src/menu"
demos.push(Demo2)


/*
 * This file is autogenerated from vite
 * via autoimport.js
 * 
 * It contains all components from src/
*/

import "../src/table"
import {Demo as Demo3} from "../src/table"
demos.push(Demo3)

            import {render} from "preact";

if(typeof window != 'undefined' && window['showcase']) {
    document.addEventListener('DOMContentLoaded', () => {
        render(<v-navwrap> <v-menu/> <v-myel /> <v-dialog open/></v-navwrap>, document.body);
    })
}
            